# Tentative Plan & Schedule {-}

## Schedule {-}
Our group will meet every two weeks. 

|  Date|  Time|  Location| Topic|
|--:|--:|--:|--:|
|  2/25|  4pm|  Cary Hall 42| Intro to group + RStudio|
|  3/10|  4pm|  TBD| TBD|
|  3/24|  4pm|  TBD| TBD|
|  4/7|  4pm|  TBD| TBD|
|  4/21|  4pm|  TBD| TBD|
|  5/5|  4pm|  TBD| TBD|

<center>
*More meet ups TBD*
</center>

At our initial meeting on 2/25, we will do the following:
- Discuss schedule of topics/workshops for the term
- Get the relevant software (Praat/R/RStudio) installed & do a quick walk through/troubleshooting so we can do as much hands-on as possible at upcoming meetings
- Preview some examples of code in each program (Praat, R)

The schedule will depend on the goals of the group. At the moment (as of late January 2020), the tentative plan is the following:

- Biweekly meet ups in the CASA Lab (104 Cary Hall, UB South Campus).
- Each meet up will involve a brief tutorial to the skill we'll be working on.
- A new challenge will be addressed at the end, which we will go over at the next meeting.

## Topic abstracts {-}

#### [Topic 1](#topic1): Intro to group, coding for speech, & RStudio {-}
This meet up will mostly serve as a means to chat logistics. We will also use this opportunity to install R, RStudio, and Praat. We will take a look at RStudio.

#### Topic 2 (*tentative*): Generate summary reports in R and R Markdown {-}
This first topic will serve as a mini introduction to R and R Studio. We will learn how to produce a short summary report using R Markdown, which allows us to integrate text and R code in the same document. These summary documents will be used as a way to keep track of our exercises and notes throughout the term, serving as a set of reference documents for us as we go along. Using R Markdown will also be useful down the line, as it can also be used to write presentations, articles, websites/blogs, and theses. For example, this website was written using R Markdown.
